--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Nelson
-- Project :      BDD2.dm1
-- Author :       Nelson
--
-- Date Created : Friday, May 29, 2020 01:10:28
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: BANCO 
--

CREATE TABLE BANCO(
    COD_BANCO       CHAR(10)        NOT NULL,
    NOMBRE_BANCO    VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (COD_BANCO)
)
;



-- 
-- TABLE: CHEQUE 
--

CREATE TABLE CHEQUE(
    NUM_CHEQUE           CHAR(10)         NOT NULL,
    ID_CUENTA            NUMBER(38, 0)    NOT NULL,
    FECHA_CHEQUE         DATE             NOT NULL,
    BENEFICIARIO         VARCHAR2(20)     NOT NULL,
    MONTO                NUMBER(20, 0)    NOT NULL,
    COD_ESTADO_CHEQUE    CHAR(10)         NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (NUM_CHEQUE)
)
;



-- 
-- TABLE: CUENTA 
--

CREATE TABLE CUENTA(
    ID_CUENTA        NUMBER(38, 0)    NOT NULL,
    COD_BANCO        CHAR(10)         NOT NULL,
    NOMBRE_CUENTA    VARCHAR2(50),
    MONTO            NUMBER(15, 0)    NOT NULL,
    RANGO_MINIMO     NUMBER(15, 0)    NOT NULL,
    RANGO_MAXIMO     NUMBER(20, 0)    NOT NULL,
    COD_USUARIO      VARCHAR2(15)     NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (ID_CUENTA)
)
;



-- 
-- TABLE: ESTADO_CHEQUE 
--

CREATE TABLE ESTADO_CHEQUE(
    COD_ESTADO_CHEQUE    CHAR(10)    NOT NULL,
    ESTADO_CHEQUE        CHAR(10),
    CONSTRAINT PK8 PRIMARY KEY (COD_ESTADO_CHEQUE)
)
;



-- 
-- TABLE: TIPO_USUARIO 
--

CREATE TABLE TIPO_USUARIO(
    COD_TIPO_USUARIO    CHAR(10)        NOT NULL,
    TIPO_USUARIO        VARCHAR2(10),
    CONSTRAINT PK3 PRIMARY KEY (COD_TIPO_USUARIO)
)
;



-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    COD_USUARIO         VARCHAR2(15)     NOT NULL,
    NOMBRE              VARCHAR2(15)     NOT NULL,
    APELLIDO            VARCHAR2(15),
    CUI                 VARCHAR2(15)     NOT NULL,
    TELEFONO            NUMBER(38, 0),
    CORREO              VARCHAR2(20)     NOT NULL,
    COD_TIPO_USUARIO    CHAR(10)         NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (COD_USUARIO)
)
;



-- 
-- TABLE: CHEQUE 
--

ALTER TABLE CHEQUE ADD CONSTRAINT RefCUENTA8 
    FOREIGN KEY (ID_CUENTA)
    REFERENCES CUENTA(ID_CUENTA)
;

ALTER TABLE CHEQUE ADD CONSTRAINT RefESTADO_CHEQUE9 
    FOREIGN KEY (COD_ESTADO_CHEQUE)
    REFERENCES ESTADO_CHEQUE(COD_ESTADO_CHEQUE)
;


-- 
-- TABLE: CUENTA 
--

ALTER TABLE CUENTA ADD CONSTRAINT RefUSUARIO6 
    FOREIGN KEY (COD_USUARIO)
    REFERENCES USUARIO(COD_USUARIO)
;

ALTER TABLE CUENTA ADD CONSTRAINT RefBANCO7 
    FOREIGN KEY (COD_BANCO)
    REFERENCES BANCO(COD_BANCO)
;


-- 
-- TABLE: USUARIO 
--

ALTER TABLE USUARIO ADD CONSTRAINT RefTIPO_USUARIO5 
    FOREIGN KEY (COD_TIPO_USUARIO)
    REFERENCES TIPO_USUARIO(COD_TIPO_USUARIO)
;


